### ISSUE TITLE
WIN10系统安装后打不开

### ISSUE THREAD

**Issue by bqf9979** [airplayx/gormat#3]
WIN10系统安装后打不开,在另一台一样系统的机器就能打开是不是需要什么库没装

**Comment by airplayx** [comment]
尝试使用管理员权限打开，或者直接以管理员命令行打开

**Comment by bqf9979** [comment]
都试了不行




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "airplayx"<notifications@github.com&gt;; 
发送时间: 2020年4月26日(星期天) 上午10:52
收件人: "airplayx/gormat"<gormat@noreply.github.com&gt;; 
抄送: "bu"<80180649@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [airplayx/gormat] WIN10系统安装后打不开 (#3)





 
尝试使用管理员权限打开，或者直接以管理员命令行打开

**Comment by airplayx** [comment]
清理一下安装目录下的config.json文件，并赋予安装目录读写权限

**Comment by bqf9979** [comment]
根本没生成这个文件,给目录everyone 全部权限了,应该是还没生成这个文件之前就崩溃了,在我另一个能用的电脑上有这个文件




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"airplayx"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月26日(星期天) 中午11:09
收件人:&nbsp;"airplayx/gormat"<gormat@noreply.github.com&gt;;
抄送:&nbsp;"bu"<80180649@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [airplayx/gormat] WIN10系统安装后打不开 (#3)





 
清理一下安装目录下的config.json文件，并赋予安装目录读写权限

**Comment by bqf9979** [comment]
要不要给你我的环境,你测一下?我QQ80180649

**Comment by airplayx** [comment]
![image](https://user-images.githubusercontent.com/8004501/83492764-56910780-a4e6-11ea-8ae7-a2700e6ee2fa.png)
远端访问造成的风险提示问题，如果有远程操作建议关闭远端的WindowsDefender软件。
